orizaba/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('app_apis.urls')),
    path('', include('app_orders.urls')),
    path('', include('app_users.urls')),
    path('', include('app_products.urls')),
    path('', include('app_utils.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_products/models.py
from django.db import models
import datetime

class MagentoProductSync(models.Model):
    product = models.ForeignKey('product', on_delete=models.CASCADE, null=True, blank=True)
    stock_qty = models.IntegerField(blank=True, default=0)
    date_added = models.DateTimeField(auto_now_add=True, blank=True, null=True)  
    date_synced = models.DateTimeField(blank=True, null=True) 
    has_synced = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id) + ' | ' + str(self.product)

    class Meta:
        ordering = ["-has_synced", "pk"]

class StockCheck(models.Model):
    product = models.ForeignKey('product', on_delete=models.CASCADE, null=True, blank=True)
    expected_qty = models.IntegerField(blank=True, default=0)
    actual_qty = models.IntegerField(blank=True, default=0)
    difference_qty = models.IntegerField(blank=True, default=0)
    date_checked = models.DateTimeField(auto_now_add=True, blank=True, null=True) 

    def __str__(self):
        return str(self.id) + ' | ' + str(self.product)

    class Meta:
        ordering = ["-id"]

class StockLocation(models.Model):
    product = models.ForeignKey('product', on_delete=models.CASCADE, null=True, blank=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True, blank=True, null=True) 

    def __str__(self):
        return str(self.id) + ' | ' + str(self.product)

    class Meta:
        ordering = ["-id"]

class StockMovement(models.Model):
    STATUS_CHOICES = [
        ('Online Sale', 'Online Sale'),
        ('Purchase Order Receipt', 'Purchase Order Receipt'),
        ('Manual Adjustment', 'Manual Adjustment'),      
    ]
    product = models.ForeignKey('product', on_delete=models.CASCADE, null=True, blank=True)
    adjustment_qty = models.IntegerField(blank=True, default=0) # Related to the quantity delivered, like in PurchaseOrderItem table
    movement_type = models.CharField(max_length=200, choices=STATUS_CHOICES, blank=True, null=True)
    date_added = models.DateTimeField(blank=True, null=True) 
    purchaseorder = models.ForeignKey('purchaseorder', on_delete=models.CASCADE, null=True, blank=True)
    order_id = models.ForeignKey('app_orders.order', db_column='order_id', on_delete=models.CASCADE, null=True, blank=True)
    current_stock_qty = models.IntegerField(default=0, blank=True, null=True)
    comments = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return str(self.product_id) + ' | ' + self.product.product_name + ' | ' + str(self.date_added) + ' | ' + str(self.adjustment_qty) + ' | ' + str(self.current_stock_qty) + ' | ' + str(self.movement_type) + ' | ' + str(self.purchaseorder)

    class Meta:
        ordering = ["-date_added", "-pk"]

class Customer(models.Model):
    customer_id = models.AutoField(primary_key=True)
    billing_email = models.CharField(max_length=200, blank=True, unique=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.billing_email) + ' | ' + str(self.date)

    class Meta:
        ordering = ["-date"]

class PurchaseOrderItem(models.Model):
    STATUS_CHOICES = [
        ('Order Pending', 'Order Pending'),
        ('Partial Receipt', 'Partial Receipt'),
        ('Full Receipt', 'Full Receipt'),
    ]
    product = models.ForeignKey('product', on_delete=models.CASCADE)
    product_sku = models.CharField(max_length=200, blank=True)
    purchaseorder = models.ForeignKey('purchaseorder', on_delete=models.CASCADE, null=True, blank=True)
    order_qty = models.IntegerField(blank=True, default=0)      
    received_qty = models.IntegerField(blank=True, default=0)   
    outstanding_qty = models.IntegerField(blank=True, default=0)    
    received_status = models.CharField(max_length=200, choices=STATUS_CHOICES, blank=True, default="Order Pending") 
    comments = models.CharField(max_length=100, blank=True, null=True)
    date_updated = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return str(self.id) + ' | ' + str(self.purchaseorder.reference) + ' | ' + str(self.product.product_name) + ' | ' + str(self.order_qty) + ' | ' + str(self.received_qty) + ' | ' + str(self.outstanding_qty) + ' | ' + str(self.received_status)

    class Meta:
        ordering = ["product_sku", "-id"]

class PurchaseOrder(models.Model):
    PO_CHOICES = [
        ('Pending', 'Pending'),
        ('Part Receipt', 'Part Receipt'),
        ('Complete', 'Complete'),
    ]
    po_id = models.AutoField(primary_key=True)
    reference = models.CharField(max_length=200, blank=True)	
    supplier_reference = models.CharField(max_length=200, blank=True)	
    supplier = models.ForeignKey('supplier', db_column='supplier', on_delete=models.CASCADE, null=True, blank=True)
    date_added = models.DateField(auto_now_add=True)
    date_ordered = models.DateField(blank=True, null=True)
    status = models.CharField(max_length=200, choices=PO_CHOICES, blank=True)
    notes = models.CharField(max_length=1000, blank=True)
    total_lines = models.IntegerField(blank=True, default=0)
    order_qty = models.IntegerField(blank=True, default=0)      
    received_qty = models.IntegerField(blank=True, default=0) 
    outstanding_qty = models.IntegerField(blank=True, default=0)    

    def __str__(self):
        return str(self.po_id) + ' | ' + str(self.reference)

    class Meta:
        ordering = ["-pk"]

class ProductLabel(models.Model):
    product = models.ForeignKey('product', on_delete=models.CASCADE, null=True, blank=True)
    qty = models.PositiveIntegerField(blank=True)
    is_printed = models.BooleanField(default=False)
    date_printed = models.DateTimeField(blank=True, null=True) 

    def __str__(self):
        return str(self.product) + ' | ' + str(self.qty) + ' | ' + str(self.date_printed)

    class Meta:
        ordering = ["id"]

class Product(models.Model):
    TYPE_CHOICES = [
        ('Part', 'Part'),
        ('Delivery', 'Delivery'),
        ('Gift', 'Gift'),
    ]
    STATUS_CHOICES = [
        ('Enabled', 'Enabled'),
        ('Disabled', 'Disabled'),
    ]
    product_id = models.IntegerField(primary_key=True)
    product_name = models.CharField(max_length=200, blank=True)	
    product_type = models.CharField(max_length=200, blank=True, choices=STATUS_CHOICES, default='Part')	
    sku = models.CharField(max_length=200, blank=True)
    buy_price = models.DecimalField(blank=True, default=0, max_digits=7, decimal_places=2)
    sell_price = models.DecimalField(blank=True, default=0, max_digits=7, decimal_places=2)
    stock_qty = models.IntegerField(blank=True, default=0) # Will be removed
    orizaba_stock_qty = models.IntegerField(blank=True, default=0) # Will eventually be changed to stock_qty
    last_stock_check = models.DateTimeField(blank=True, null=True)
    item_profit = models.DecimalField(blank=True, default=0, max_digits=7, decimal_places=2)
    stock_profit = models.DecimalField(blank=True, default=0, max_digits=7, decimal_places=2)
    buy_value = models.DecimalField(blank=True, default=0, max_digits=7, decimal_places=2)
    sell_value = models.DecimalField(blank=True, default=0, max_digits=7, decimal_places=2)  
    profit_margin = models.DecimalField(blank=True, default=0, max_digits=7, decimal_places=2)    
    weight = models.DecimalField(blank=True, default=0, max_digits=7, decimal_places=4)
    location = models.CharField(max_length=200, blank=True, null=True)	
    part_type = models.CharField(max_length=200, blank=True, default='null')	
    brand = models.ForeignKey('brand', db_column='brand', on_delete=models.CASCADE, null=True, blank=True, default='Other')
    supplier = models.ForeignKey('supplier', db_column='supplier', on_delete=models.CASCADE, null=True, blank=True, default='Unknown')
    url = models.CharField(max_length=200, blank=True, default='null')
    status = models.CharField(max_length=200, blank=True, choices=STATUS_CHOICES, default='Enabled')	
    has_image = models.BooleanField(default=False) 
    product_image = models.ImageField(upload_to="images/products", null=True, blank=True)
    condition = models.CharField(max_length=200, blank=True, default='new')	
    special_order = models.CharField(max_length=200, blank=True, default='no')	
    sealed_item = models.BooleanField(default=False)

    def __str__(self):
        return str(self.sku)

    class Meta:
        ordering = ["product_id", "location"]

    @property
    def product_calcs(self, *args, **kwargs):
        # Calculate - Buy Value, Sell Value, Profit Per Item, Total Stock Profit
        self.buy_value = (self.buy_price * self.stock_qty)
        self.sell_value = (self.sell_price * self.stock_qty)
        self.item_profit = (self.sell_price - self.buy_price)
        self.stock_profit = (self.sell_value - self.buy_value)
        # Calculate the Profit Margin on the item
        if self.sell_price != 0:
            profit = ((self.item_profit / self.sell_price) * 100) 
            self.profit_margin = round(profit, 0)
        else:
            self.profit_margin = 0
        super(Product, self).save(*args, **kwargs)
        return ''
    
class Supplier(models.Model):
    supplier = models.CharField(max_length=200, primary_key=True)
    path = models.CharField(max_length=200, blank=True)
    sort_order = models.IntegerField(default=100)

    def __str__(self):
        return self.supplier

    class Meta:
        ordering = ["sort_order"]

class Brand(models.Model):
    brand = models.CharField(max_length=200, primary_key=True)
    path = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.brand

    class Meta:
        ordering = ["brand"]


templates/app_products/purchase_order_detail_new/components/items.html
{% load static %}
<div>
    <h2>Purchase Order Items&nbsp;&nbsp;&nbsp;<i id="open-part-add" class="far fa-plus-square"></i></h2>
    <form id="po_item_form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ po_item_form.management_form }}
        <!-- EXPANDABLE SECTION FOR ADDING A PART -->
        <!-- GENERATED VIA THE jS PURCHASE-ORDER-DETAIL.JS LINE 125 -->
        <div class="add-po-item">
            <input class="po-id" type="hidden" value="1">
            <input class="po-item-id" type="hidden">
            <input class="po-item-product" type="hidden">
            <input class="po-item-product-sku" type="hidden">
            <div class="po-item-product">
                <b>Product SKU:</b>
                <div>
                    <input type="text">
                    <div id="match-list"></div>
                </div>
            </div>
            <div class="po-item-qty">
                <b>Qty:</b>
                <div>
                    <input type="number" value="1" min="1">
                </div>
            </div>
            <div class="po-item-button">
                &nbsp;
                <div>
                    <button>Add Part</button>
                </div>
            </div>
            <div id="close-part-add" onclick="closeAddBlock()"><i class="far fa-window-close"></i></div>
        </div>    
        <!-- JAVASCRIPT FILTER OF THE LIST -->
        <!-- HIDDEN WHEN THE ADD PURCHASE ORDER SECTION IS OPEN --> 
        <div class="po-filter">
            <b>SKU Filter: </b><input id="sku-input" type="text" value="" />
        </div>
        <!-- MAIN TABLE DISPLAYING ALL ADDED PARTS -->    
        <table cellpadding="0" cellspacing="0">                         
            <thead>
                <tr>
                    <th></th>
                    <th>#</th>
                    <th>SKU</th>
                    <th>Part Name</th>
                    <th>Ordered</th>
                    <th>Received</th>
                    <th>Outstanding</th>
                    <th>Label / Add</th>
                    <th>Stock</th>
                    <th>Comments</th>
                </tr>
            </thead>
            <tbody>       
                {% for item in po_items %}
                <tr class="part-row {% cycle 'row1' 'row2' %}" onclick="closeAddBlock()">
                    <td class="icon-right">&nbsp;</td>
                    <td class="col-40 part-count"><b>{{ forloop.counter }}</b></td>
                    <td class="col-80 part-sku">{{ item.product.sku }}{{ item.product }}{{ item.product_sku }}</td>
                    <td class="col-300"><a href="{% url 'product-detail' item.product.pk %}">{{ item.product.product_name }}</a></td>
                    <td class="col-60 part-ordered">{{ item.order_qty }}</td>
                    <td class="col-60 part-received">{{ item.received_qty }}</td>
                    <td class="col-60 part-outstanding">{{ item.outstanding_qty }}<span></span></td>
                    <td class="col-60 received-select">
                        {{ item.label }}
                        <select class="part-select" type="number" data="select" name="purchaseorderitem_set-{{ forloop.counter0 }}-delivery_qty" id="id_purchaseorderitem_set-{{ forloop.counter0 }}-delivery_qty" onchange="this.form.submit()">
                        {% with ''|center:item.outstanding_qty as range %}
                            <option class="blank-option" name="item" value="0">--</option>
                            {% for _ in range %}
                            <option name="item" value="{{ forloop.counter }}">{{ forloop.counter }}</option>
                            {% endfor %}
                        {% endwith %}
                        </select>     
                    </td>
                    <td class="col-40 stock"><span>{{ item.instance.product.stock_qty }}</span></td>                    
                    <td class="comments">
                        <div class="show">
                            {% if item.comments %}
                                {{ item.comments}} 
                            {% else %}
                                <i class="fas fa-edit"></i>
                            {% endif %}
                            <span>
                                {% if item.date_updated %}
                                    <i><b>{{ item.received_status }}</b>&nbsp;&nbsp;-&nbsp;&nbsp;
                                {% endif %}
                                    <span class="date-received">{{ item.date_updated|date:'D d M Y' }}</span></i>
                            </span>
                        </div>
                        <div class="edit">
                            {{ item.comments }}<button type="submit"><i class="fas fa-check"></i></button>
                            <input class="date_updated" type="hidden" name="purchaseorderitem_set-{{ forloop.counter0 }}-date_updated" value="{{ item.instance.date_updated|date:'Y-m-d' }}" id="id_purchaseorderitem_set-{{ forloop.counter0 }}-date_updated">
                        </div>
                    </td>
                </tr>
                <tr>
                    <!-- APPENDS extra-image CLASS TO THE BELOW DIV WHEN THE ROW IS SELECTED -->
                    <td class="product-image" colspan=10>
                        <div class="extra-content">                 
                            <div class="extra-image">
                                {% if item.instance.product.product_image == 'img/no-image.png' %}
                                    <img src="https://www.gardentractorspares.co.uk/media/catalog/product/{% comment %}{{ item.instance.product.image }}{% endcomment %}" />
                                {% else %}
                                     <img src="/static/media/{{ item.product.product_image }}">
                                {% endif %}
                            </div>  
                            <!-- FURTHER ACTIONS SECTION -->
                            <div class="further-actions">
                                <h3>Further Actions</h3>
                                <div>
                                    <span class="title">Edit Order Qty:</span>
                                    <span class="edit-qty">{{ item.order_qty }}<button>Edit</button></span>
                                    {% if item.received_qty != 0 %}  
                                        <span class="title">Reset Receipt Qty:</span>
                                        <span class="reset-receipt"><input hidden disabled value="-{{ item.instance.received_qty }}" name="purchaseorderitem_set-{{ forloop.counter0 }}-delivery_qty" id="id_purchaseorderitem_set-{{ forloop.counter0 }}-delivery_qty"><button type="submit">Reset</button></span>  
                                    {% endif %}
                                    {% if item.received_qty == 0 %}             
                                        <span class="title">Delete Part from PO:</span>
                                        <span class="delete-part">{{ item.DELETE }}<button>Delete</button></span>
                                    {% endif %}
                                </div>
                            </div>   
                        </div>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td class="empty" colspan="10">
                        There are no purchase order items to display. 
                    </td>
                </tr>
                {% endfor %}            
            </tbody>
        </table>
    </form>
</div>